### ISSUE TITLE
Fail build in linux (commit 8eb9bd5 . hevc_rext branch)

### ISSUE THREAD

**Issue by sl1pkn07** [OpenHEVC/openHEVC#30]
Hi

When try to build this commit (8eb9bd5), make a fail build

```
[  9%] Building C object CMakeFiles/LibOpenHevcWrapper.dir/libavutil/avstring.c.o
cc: fatal error: no input files
compilation terminated.
/bin/sh: -Wl,-Bsymbolic: command not found
CMakeFiles/LibOpenHevcWrapper.dir/build.make:129: recipe for target 'CMakeFiles/LibOpenHevcWrapper.dir/libavutil/avstring.c.o' failed
make[2]: *** [CMakeFiles/LibOpenHevcWrapper.dir/libavutil/avstring.c.o] Error 127
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/LibOpenHevcWrapper.dir/all' failed
make[1]: *** [CMakeFiles/LibOpenHevcWrapper.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
```

Builded on linux with GCC5 with:

```
cd build
cmake ../openhevc \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DCMAKE_BUILD_TYPE=RELEASE \
  -DCMAKE_SKIP_RPATH=ON
make
```

cmake log:

http://sl1pkn07.wtf/paste/view/e4828ad2

greetings

**Comment by mraulet** [comment]
can you let us know whether the compilation has worked for you before using gcc 5? Have you been able to manage compilation with an older version of gcc?

**Comment by sl1pkn07** [comment]
Hi

I have the same problem with clang (3.6.1)

The latest version that I have compiled is 9faaba6, but I don't remember with what gcc

9faaba6 build ok with gcc5

give me time to see which commit is to blame for the regression

**Comment by sl1pkn07** [comment]
since (inclusive) 95ca8a74d81e5cd5171bcf67d07096d6047713f4 start the fail build

**Comment by eraffin** [comment]
Hello,
Could you please try with the latest version?

**Comment by sl1pkn07** [comment]
--need test again--

**Comment by eraffin** [comment]
Good, thanks for your feedback.
Fixed in commit dab2116...

**Comment by sl1pkn07** [comment]
oh sorr, need test again, because i not switch to correct branch.

EDIT: build with clang works ok, but still fail with GCC5 in same point

log with clang:
    http://sl1pkn07.wtf/paste/view/10a97f26  (see warning about C99 code(?))
log with GCC 5:
    http://sl1pkn07.wtf/paste/view/aa652d71

**Comment by eraffin** [comment]
No issue on my side when compiling with GCC 5... Your problem seems to be related to your build environment.
Could you provide compilation log using "make VERBOSE=1"?

**Comment by sl1pkn07** [comment]
with VERBOSE=1

http://sl1pkn07.wtf/paste/view/966ed065

greetings

**Comment by eraffin** [comment]
Thanks, could you try with the updated version?

**Comment by sl1pkn07** [comment]
Build OK. now fixed. thanks!
